//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilgimYok {
    
    
    public partial class Default {
        
        /// <summary>
        /// Slider1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bilgimYok.UserControl.SliderMiddleBig Slider1;
        
        /// <summary>
        /// SliderRightTop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bilgimYok.UserControl.SliderRightTop SliderRightTop1;
        
        /// <summary>
        /// OrtakKullanim1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bilgimYok.UserControl.OrtakKullanim OrtakKullanim1;
    }
}
